name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    # The type of runner that the job will run on
    runs-on: macos-12

    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Select Xcode 
      run: sudo xcode-select -switch /Applications/Xcode_14.1.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build and test
      run: xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO